[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "terestun"
version = "0.0.1"
authors = [
  { name="ValdikSS", email="iam@valdikss.org.ru" },
]
description = "STUN client using Teredo protocol"
readme = "README.md"
requires-python = ">=3.4"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/valdikss/terestun"
"Bug Tracker" = "https://github.com/valdikss/terestun/issues"
